// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var bob = {
  id: 1,
  name: "Bob"
};

function greet(person) {
  return "Hello, " + (person.name + (" with id " + String(person.id)));
}

var jim = {
  id: 2,
  name: "Jimbo",
  age: 29
};

console.log(greet(jim));

var moreLiteral = {
  id: 42,
  things: /* :: */[
    "x",
    /* :: */[
      "y",
      /* :: */[
        "z",
        /* [] */0
      ]
    ]
  ]
};

console.log(moreLiteral);

exports.bob = bob;
exports.greet = greet;
exports.jim = jim;
exports.moreLiteral = moreLiteral;
/*  Not a pure module */
