// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function summarize(array) {
  var result = /* record */[
    /* count */array.length,
    /* mean */0,
    /* sum */0
  ];
  for(var i = 0 ,i_finish = result[/* count */0] - 1 | 0; i <= i_finish; ++i){
    result[2] += array[i];
  }
  result[/* mean */1] = result[/* sum */2] / result[/* count */0];
  return result;
}

exports.summarize = summarize;
/* No side effect */
