// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Ch04_RecordLiterals$PacktTypeDrivenDev = require("./Ch04_RecordLiterals.bs.js");

var bob_000 = /* id */Ch04_RecordLiterals$PacktTypeDrivenDev.bob[/* id */0];

var bob_000$1 = bob_000;

var bob = /* record */[
  bob_000$1,
  /* name */"Robert"
];

exports.bob = bob;
/* No side effect */
