// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


console.log(1);

console.log(1, 2);

var bob = /* tuple */[
  1,
  "Bob"
];

var jim = /* tuple */[
  "Jim",
  2
];

var bobName = "Bob";

var jimName = "Jim";

var bobId = 1;

var jimId = 2;

var tom = /* tuple */[
  3,
  "tom",
  45
];

exports.bob = bob;
exports.jim = jim;
exports.bobName = bobName;
exports.jimName = jimName;
exports.bobId = bobId;
exports.jimId = jimId;
exports.tom = tom;
/*  Not a pure module */
