// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var jim = /* record */[
  /* id */2,
  /* name */"Jim"
];

var bob = /* record */[
  /* id */1,
  /* name */"Bob"
];

var tom = /* record */[
  /* id */42,
  /* name */"Thomas"
];

exports.bob = bob;
exports.jim = jim;
exports.tom = tom;
/* No side effect */
