// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function infoAboutShoe(s) {
  if (s >= 106377731) {
    if (s >= 351714595) {
      if (s >= 1049790605) {
        return "high heels (w)";
      } else {
        return "wingtips";
      }
    } else if (s >= 265261402) {
      return "mocs";
    } else {
      return "slingbacks (w)";
    }
  } else if (s >= -326854350) {
    return "sneaks";
  } else {
    return "boots";
  }
}

console.log(infoAboutShoe(/* Moccasins */265261402));

console.log(infoAboutShoe(/* Slingbacks */106377731));

function infoAboutShoe2(s) {
  if (s !== 265261402) {
    if (s >= 106377731) {
      if (s !== 351714595) {
        return "Woman shoe such as Sandals or High Heels";
      } else {
        return "Wingtips";
      }
    } else if (s >= -326854350) {
      return "Sneakers";
    } else {
      return "Boots";
    }
  } else {
    return "Moccasins";
  }
}

console.log(infoAboutShoe(/* Moccasins */265261402));

console.log(infoAboutShoe(/* Slingbacks */106377731));

var johnDoeShoe = /* Moccasins */265261402;

var janeDoeShoe = /* Slingbacks */106377731;

exports.johnDoeShoe = johnDoeShoe;
exports.janeDoeShoe = janeDoeShoe;
exports.infoAboutShoe = infoAboutShoe;
exports.infoAboutShoe2 = infoAboutShoe2;
/*  Not a pure module */
