// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


console.log(/* Green */756711075);

console.log(/* Green */756711075);

function stringOfColor(c) {
  if (c !== 4100401) {
    if (c >= 737308346) {
      if (c >= 756711075) {
        return "green";
      } else {
        return "blue";
      }
    } else if (c >= 82908052) {
      return "yellow";
    } else {
      return "orange";
    }
  } else {
    return "red";
  }
}

function stringOfRgb(c) {
  if (c !== 737308346) {
    if (c >= 756711075) {
      return "RGB green";
    } else {
      return "RGB red";
    }
  } else {
    return "RGB blue";
  }
}

console.log(stringOfColor(/* Green */756711075));

console.log(stringOfRgb(/* Green */756711075));

var oneGreen = /* Green */756711075;

var otherGreen = /* Green */756711075;

exports.oneGreen = oneGreen;
exports.otherGreen = otherGreen;
exports.stringOfColor = stringOfColor;
exports.stringOfRgb = stringOfRgb;
/*  Not a pure module */
