// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Ch09_OpenModule$PacktTypeDrivenDev = require("./Ch09_OpenModule.bs.js");

console.log(Ch09_OpenModule$PacktTypeDrivenDev.ColorExample[/* stringOfColor */2](Ch09_OpenModule$PacktTypeDrivenDev.ColorExample[/* onegreen */0]));

console.log(Ch09_OpenModule$PacktTypeDrivenDev.ColorExample[/* stringOfRgb */3](Ch09_OpenModule$PacktTypeDrivenDev.ColorExample[/* othergreen */1]));

console.log("String value of another color: " + Ch09_OpenModule$PacktTypeDrivenDev.ColorExample[/* stringOfColor */2](/* Blue */737308346));

var colorString = /* () */0;

exports.colorString = colorString;
/*  Not a pure module */
