// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE


function makePerson(id, name) {
  return /* record */[
          /* id */id,
          /* name */name
        ];
}

var bob = /* record */[
  /* id */42,
  /* name */"Bobish"
];

export {
  makePerson ,
  bob ,
  
}
/* No side effect */
