// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function makePerson(id, name) {
  return /* record */[
          /* id */id,
          /* name */name
        ];
}

var bob = /* record */[
  /* id */42,
  /* name */"Bobish"
];

exports.makePerson = makePerson;
exports.bob = bob;
/* No side effect */
