// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function makePerson(id, name, nic) {
  return /* record */[
          /* id */id,
          /* name */name,
          /* nic */nic
        ];
}

exports.makePerson = makePerson;
/* No side effect */
