// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function makeExn(string) {
  if (string === "") {
    throw [
          Caml_builtin_exceptions.assert_failure,
          /* tuple */[
            "Ch07_DomainTypes.re",
            7,
            4
          ]
        ];
  }
  return string;
}

var NonEmptyString = /* module */[/* makeExn */makeExn];

function makeExn$1($$float) {
  if ($$float <= 0) {
    throw [
          Caml_builtin_exceptions.assert_failure,
          /* tuple */[
            "Ch07_DomainTypes.re",
            18,
            4
          ]
        ];
  }
  return $$float;
}

var PositiveFloat = /* module */[/* makeExn */makeExn$1];

function sendMoney(from, to_, amount) {
  console.log("Send \$" + (String(amount) + (" from " + (String(from) + (" to " + (String(to_) + ""))))));
  return /* () */0;
}

sendMoney(makeExn("Alice"), makeExn("Bob"), makeExn$1(32));

exports.NonEmptyString = NonEmptyString;
exports.PositiveFloat = PositiveFloat;
exports.sendMoney = sendMoney;
/*  Not a pure module */
