// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as $$String from "bs-platform/lib/es6/string.js";

function id(t) {
  return t[/* id */0];
}

function name(t) {
  return t[/* name */1];
}

function make(id, name) {
  return /* record */[
          /* id */id,
          /* name */$$String.trim($$String.capitalize(name))
        ];
}

export {
  make ,
  id ,
  name ,
  
}
/* No side effect */
