// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function make(id, name) {
  return /* record */[
          /* id */id,
          /* name */$$String.trim($$String.capitalize(name))
        ];
}

function fnord(param) {
  return "hi";
}

var Person = /* module */[
  /* make */make,
  /* fnord */fnord
];

exports.Person = Person;
/* No side effect */
