// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Ch03_Person$PacktTypeDrivenDev = require("./Ch03_Person.bs.js");

var p2 = Ch03_Person$PacktTypeDrivenDev.make(2, Ch03_Person$PacktTypeDrivenDev.Name[/* make */0](" alex "));

console.log(p2);

exports.p2 = p2;
/* p2 Not a pure module */
