// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function make($$int) {
  return $$int;
}

function toInt(t) {
  return t;
}

var IntId = /* module */[
  /* make */make,
  /* toInt */toInt
];

var PersonId = IntId;

var CompanyId = IntId;

var bobId = 1;

var acmeCoId = 1;

exports.IntId = IntId;
exports.PersonId = PersonId;
exports.CompanyId = CompanyId;
exports.bobId = bobId;
exports.acmeCoId = acmeCoId;
/* No side effect */
