// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE


var age = "33";

var greeting = "Hello, Bob aged 34";

var name = "Jim";

var greeting2 = "Hello, Jim aged 33";

export {
  age ,
  greeting ,
  name ,
  greeting2 ,
  
}
/* No side effect */
