// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function apps(company) {
  switch (company) {
    case 0 : 
        return "facebook, messenger, ads";
    case 1 : 
        return "gmail, search, maps, ads";
    case 2 : 
        return "twitter";
    
  }
}

var googleApps = "gmail, search, maps, ads";

console.log(googleApps);

exports.apps = apps;
exports.googleApps = googleApps;
/*  Not a pure module */
