// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function appToString(app) {
  return app[/* name */0] + (" (" + (app[/* url */1] + ")"));
}

exports.appToString = appToString;
/* No side effect */
