// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var facebook = /* record */[
  /* name */"facebook",
  /* url */"https://facebook.com"
];

var facebookads = /* record */[
  /* name */"facebook ads",
  /* url */"https://www.facebook.com/business"
];

var messenger = /* record */[
  /* name */"messenger",
  /* url */"https://www.facebook.com/messenger"
];

var instagram = /* record */[
  /* name */"instagram",
  /* url */"https://www.instagram.com"
];

exports.facebook = facebook;
exports.facebookads = facebookads;
exports.messenger = messenger;
exports.instagram = instagram;
/* No side effect */
