// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var bobEdu = /* College */1;

var bobPaymentMethod = /* Cash */0;

var jimEducation = /* Other */3;

var jimPaymentMethod = /* PurchaseOrder */["jimbo997"];

exports.bobEdu = bobEdu;
exports.bobPaymentMethod = bobPaymentMethod;
exports.jimEducation = jimEducation;
exports.jimPaymentMethod = jimPaymentMethod;
/* No side effect */
