// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function stringToColor(string) {
  switch (string) {
    case "blue" : 
        return /* blue */-1055309158;
    case "green" : 
        return /* green */434966211;
    case "red" : 
        return /* red */5691729;
    default:
      return /* unknown */-512023670;
  }
}

exports.stringToColor = stringToColor;
/* No side effect */
