// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function paymentMethodThanks(paymentMethod) {
  if (paymentMethod) {
    return "Thanks for your PO " + paymentMethod[0];
  } else {
    return "We always love cash!";
  }
}

console.log("We always love cash!");

var msg = "Thanks for your PO x99b";

console.log(msg);

exports.paymentMethodThanks = paymentMethodThanks;
exports.msg = msg;
/*  Not a pure module */
