// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var color = /* Red */4100401;

var angle = /* `degrees */[
  979035047,
  45.0
];

var pressA = /* `keypress */[
  -104560252,
  /* "a" */97
];

var shakeThrice = /* `deviceShake */[
  -346222000,
  3
];

exports.color = color;
exports.angle = angle;
exports.pressA = pressA;
exports.shakeThrice = shakeThrice;
/* No side effect */
