// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var bob = /* record */[
  /* id */1,
  /* name */"Bob",
  /* education : College */1
];

var jim = /* record */[
  /* id */2,
  /* name */"Jim",
  /* education : Other */3
];

exports.bob = bob;
exports.jim = jim;
/* No side effect */
