// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

var optionArr = /* array */[undefined];

var optionRef = /* record */[/* contents */undefined];

function pair(x) {
  return /* tuple */[
          x,
          x
        ];
}

function pairAll(list) {
  return List.map(pair, list);
}

exports.optionArr = optionArr;
exports.optionRef = optionRef;
exports.pair = pair;
exports.pairAll = pairAll;
/* No side effect */
