// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Ch06_List$PacktTypeDrivenDev = require("./Ch06_List.bs.js");
var Ch04_RecordLiterals$PacktTypeDrivenDev = require("../ch04/Ch04_RecordLiterals.bs.js");

var people_001 = /* :: */[
  Ch04_RecordLiterals$PacktTypeDrivenDev.jim,
  /* :: */[
    Ch04_RecordLiterals$PacktTypeDrivenDev.tom,
    /* [] */0
  ]
];

var people = /* :: */[
  Ch04_RecordLiterals$PacktTypeDrivenDev.bob,
  people_001
];

function greetAll(_people) {
  while(true) {
    var people = _people;
    if (people) {
      Ch06_List$PacktTypeDrivenDev.greetOne(people[0]);
      _people = people[1];
      continue ;
    } else {
      return /* () */0;
    }
  };
}

exports.people = people;
exports.greetAll = greetAll;
/* No side effect */
